services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: b4after
      POSTGRES_PASSWORD: b4after
      POSTGRES_DB: b4after
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
