// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyViewsByComparison = `-- name: GetDailyViewsByComparison :many
SELECT DATE(created_at) as date, COUNT(*)::int as count
FROM analytics
WHERE comparison_id = $1 AND event_type = 'view'
  AND (clerk_user_id IS NULL OR clerk_user_id != (SELECT user_id FROM comparisons WHERE id = $1))
GROUP BY DATE(created_at)
ORDER BY date DESC
LIMIT 30
`

type GetDailyViewsByComparisonRow struct {
	Date  pgtype.Date `json:"date"`
	Count int32       `json:"count"`
}

func (q *Queries) GetDailyViewsByComparison(ctx context.Context, comparisonID pgtype.UUID) ([]GetDailyViewsByComparisonRow, error) {
	rows, err := q.db.Query(ctx, getDailyViewsByComparison, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyViewsByComparisonRow{}
	for rows.Next() {
		var i GetDailyViewsByComparisonRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventCountsByComparison = `-- name: GetEventCountsByComparison :many
SELECT event_type, COUNT(*)::int as count
FROM analytics WHERE comparison_id = $1
  AND (clerk_user_id IS NULL OR clerk_user_id != (SELECT user_id FROM comparisons WHERE id = $1))
GROUP BY event_type
`

type GetEventCountsByComparisonRow struct {
	EventType AnalyticsEventType `json:"event_type"`
	Count     int32              `json:"count"`
}

func (q *Queries) GetEventCountsByComparison(ctx context.Context, comparisonID pgtype.UUID) ([]GetEventCountsByComparisonRow, error) {
	rows, err := q.db.Query(ctx, getEventCountsByComparison, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventCountsByComparisonRow{}
	for rows.Next() {
		var i GetEventCountsByComparisonRow
		if err := rows.Scan(&i.EventType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventCountsByCountry = `-- name: GetEventCountsByCountry :many
SELECT country, COUNT(*)::int as count
FROM analytics
WHERE comparison_id = $1 AND country IS NOT NULL AND country != ''
  AND (clerk_user_id IS NULL OR clerk_user_id != (SELECT user_id FROM comparisons WHERE id = $1))
GROUP BY country
ORDER BY count DESC
LIMIT 20
`

type GetEventCountsByCountryRow struct {
	Country pgtype.Text `json:"country"`
	Count   int32       `json:"count"`
}

func (q *Queries) GetEventCountsByCountry(ctx context.Context, comparisonID pgtype.UUID) ([]GetEventCountsByCountryRow, error) {
	rows, err := q.db.Query(ctx, getEventCountsByCountry, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventCountsByCountryRow{}
	for rows.Next() {
		var i GetEventCountsByCountryRow
		if err := rows.Scan(&i.Country, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventCountsByDevice = `-- name: GetEventCountsByDevice :many
SELECT device::text as device, COUNT(*)::int as count
FROM analytics
WHERE comparison_id = $1 AND device IS NOT NULL
  AND (clerk_user_id IS NULL OR clerk_user_id != (SELECT user_id FROM comparisons WHERE id = $1))
GROUP BY device
ORDER BY count DESC
`

type GetEventCountsByDeviceRow struct {
	Device string `json:"device"`
	Count  int32  `json:"count"`
}

func (q *Queries) GetEventCountsByDevice(ctx context.Context, comparisonID pgtype.UUID) ([]GetEventCountsByDeviceRow, error) {
	rows, err := q.db.Query(ctx, getEventCountsByDevice, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventCountsByDeviceRow{}
	for rows.Next() {
		var i GetEventCountsByDeviceRow
		if err := rows.Scan(&i.Device, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventCountsByReferrer = `-- name: GetEventCountsByReferrer :many
SELECT referrer, COUNT(*)::int as count
FROM analytics
WHERE comparison_id = $1 AND referrer IS NOT NULL AND referrer != ''
  AND (clerk_user_id IS NULL OR clerk_user_id != (SELECT user_id FROM comparisons WHERE id = $1))
GROUP BY referrer
ORDER BY count DESC
LIMIT 20
`

type GetEventCountsByReferrerRow struct {
	Referrer pgtype.Text `json:"referrer"`
	Count    int32       `json:"count"`
}

func (q *Queries) GetEventCountsByReferrer(ctx context.Context, comparisonID pgtype.UUID) ([]GetEventCountsByReferrerRow, error) {
	rows, err := q.db.Query(ctx, getEventCountsByReferrer, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventCountsByReferrerRow{}
	for rows.Next() {
		var i GetEventCountsByReferrerRow
		if err := rows.Scan(&i.Referrer, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByComparison = `-- name: ListEventsByComparison :many
SELECT id, comparison_id, event_type, device, referrer, country, created_at
FROM analytics
WHERE comparison_id = $1
  AND (clerk_user_id IS NULL OR clerk_user_id != (SELECT user_id FROM comparisons WHERE id = $1))
ORDER BY created_at DESC
`

type ListEventsByComparisonRow struct {
	ID           pgtype.UUID        `json:"id"`
	ComparisonID pgtype.UUID        `json:"comparison_id"`
	EventType    AnalyticsEventType `json:"event_type"`
	Device       NullDeviceType     `json:"device"`
	Referrer     pgtype.Text        `json:"referrer"`
	Country      pgtype.Text        `json:"country"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEventsByComparison(ctx context.Context, comparisonID pgtype.UUID) ([]ListEventsByComparisonRow, error) {
	rows, err := q.db.Query(ctx, listEventsByComparison, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByComparisonRow{}
	for rows.Next() {
		var i ListEventsByComparisonRow
		if err := rows.Scan(
			&i.ID,
			&i.ComparisonID,
			&i.EventType,
			&i.Device,
			&i.Referrer,
			&i.Country,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEvent = `-- name: RecordEvent :exec
INSERT INTO analytics (comparison_id, event_type, device, referrer, country, clerk_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordEventParams struct {
	ComparisonID pgtype.UUID        `json:"comparison_id"`
	EventType    AnalyticsEventType `json:"event_type"`
	Device       NullDeviceType     `json:"device"`
	Referrer     pgtype.Text        `json:"referrer"`
	Country      pgtype.Text        `json:"country"`
	ClerkUserID  pgtype.Text        `json:"clerk_user_id"`
}

func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) error {
	_, err := q.db.Exec(ctx, recordEvent,
		arg.ComparisonID,
		arg.EventType,
		arg.Device,
		arg.Referrer,
		arg.Country,
		arg.ClerkUserID,
	)
	return err
}
