// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyViewsByComparison = `-- name: GetDailyViewsByComparison :many
SELECT DATE(created_at) as date, COUNT(*)::int as count
FROM analytics
WHERE comparison_id = $1 AND event_type = 'view'
GROUP BY DATE(created_at)
ORDER BY date DESC
LIMIT 30
`

type GetDailyViewsByComparisonRow struct {
	Date  pgtype.Date `json:"date"`
	Count int32       `json:"count"`
}

func (q *Queries) GetDailyViewsByComparison(ctx context.Context, comparisonID pgtype.UUID) ([]GetDailyViewsByComparisonRow, error) {
	rows, err := q.db.Query(ctx, getDailyViewsByComparison, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyViewsByComparisonRow{}
	for rows.Next() {
		var i GetDailyViewsByComparisonRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventCountsByComparison = `-- name: GetEventCountsByComparison :many
SELECT event_type, COUNT(*)::int as count
FROM analytics WHERE comparison_id = $1
GROUP BY event_type
`

type GetEventCountsByComparisonRow struct {
	EventType AnalyticsEventType `json:"event_type"`
	Count     int32              `json:"count"`
}

func (q *Queries) GetEventCountsByComparison(ctx context.Context, comparisonID pgtype.UUID) ([]GetEventCountsByComparisonRow, error) {
	rows, err := q.db.Query(ctx, getEventCountsByComparison, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventCountsByComparisonRow{}
	for rows.Next() {
		var i GetEventCountsByComparisonRow
		if err := rows.Scan(&i.EventType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEvent = `-- name: RecordEvent :exec
INSERT INTO analytics (comparison_id, event_type, device, referrer, country)
VALUES ($1, $2, $3, $4, $5)
`

type RecordEventParams struct {
	ComparisonID pgtype.UUID        `json:"comparison_id"`
	EventType    AnalyticsEventType `json:"event_type"`
	Device       NullDeviceType     `json:"device"`
	Referrer     pgtype.Text        `json:"referrer"`
	Country      pgtype.Text        `json:"country"`
}

func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) error {
	_, err := q.db.Exec(ctx, recordEvent,
		arg.ComparisonID,
		arg.EventType,
		arg.Device,
		arg.Referrer,
		arg.Country,
	)
	return err
}
