// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comparisons.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countComparisonsBySpaceID = `-- name: CountComparisonsBySpaceID :one
SELECT COUNT(*) FROM comparisons WHERE space_id = $1
`

func (q *Queries) CountComparisonsBySpaceID(ctx context.Context, spaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countComparisonsBySpaceID, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComparisonsByTenantID = `-- name: CountComparisonsByTenantID :one
SELECT COUNT(*) FROM comparisons WHERE tenant_id = $1
`

func (q *Queries) CountComparisonsByTenantID(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countComparisonsByTenantID, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComparisonsByUserID = `-- name: CountComparisonsByUserID :one
SELECT COUNT(*) FROM comparisons WHERE user_id = $1
`

func (q *Queries) CountComparisonsByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countComparisonsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComparison = `-- name: CreateComparison :one
INSERT INTO comparisons (user_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, process_images, space_id, source, upload_request_id, tenant_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by
`

type CreateComparisonParams struct {
	UserID          string             `json:"user_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Slug            string             `json:"slug"`
	Category        ComparisonCategory `json:"category"`
	BeforeImageUrl  string             `json:"before_image_url"`
	AfterImageUrl   string             `json:"after_image_url"`
	BeforeLabel     string             `json:"before_label"`
	AfterLabel      string             `json:"after_label"`
	CtaText         pgtype.Text        `json:"cta_text"`
	CtaUrl          pgtype.Text        `json:"cta_url"`
	ProcessImages   []byte             `json:"process_images"`
	SpaceID         pgtype.UUID        `json:"space_id"`
	Source          ComparisonSource   `json:"source"`
	UploadRequestID pgtype.UUID        `json:"upload_request_id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	CreatedBy       pgtype.Text        `json:"created_by"`
}

func (q *Queries) CreateComparison(ctx context.Context, arg CreateComparisonParams) (Comparison, error) {
	row := q.db.QueryRow(ctx, createComparison,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Slug,
		arg.Category,
		arg.BeforeImageUrl,
		arg.AfterImageUrl,
		arg.BeforeLabel,
		arg.AfterLabel,
		arg.CtaText,
		arg.CtaUrl,
		arg.ProcessImages,
		arg.SpaceID,
		arg.Source,
		arg.UploadRequestID,
		arg.TenantID,
		arg.CreatedBy,
	)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Category,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.BeforeLabel,
		&i.AfterLabel,
		&i.CtaText,
		&i.CtaUrl,
		&i.IsPublished,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessImages,
		&i.SpaceID,
		&i.Source,
		&i.UploadRequestID,
		&i.TenantID,
		&i.CreatedBy,
	)
	return i, err
}

const deleteComparison = `-- name: DeleteComparison :exec
DELETE FROM comparisons WHERE id = $1
`

func (q *Queries) DeleteComparison(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComparison, id)
	return err
}

const getComparisonByID = `-- name: GetComparisonByID :one
SELECT id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by FROM comparisons WHERE id = $1
`

func (q *Queries) GetComparisonByID(ctx context.Context, id pgtype.UUID) (Comparison, error) {
	row := q.db.QueryRow(ctx, getComparisonByID, id)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Category,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.BeforeLabel,
		&i.AfterLabel,
		&i.CtaText,
		&i.CtaUrl,
		&i.IsPublished,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessImages,
		&i.SpaceID,
		&i.Source,
		&i.UploadRequestID,
		&i.TenantID,
		&i.CreatedBy,
	)
	return i, err
}

const getComparisonBySlug = `-- name: GetComparisonBySlug :one
SELECT id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by FROM comparisons WHERE slug = $1
`

func (q *Queries) GetComparisonBySlug(ctx context.Context, slug string) (Comparison, error) {
	row := q.db.QueryRow(ctx, getComparisonBySlug, slug)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Category,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.BeforeLabel,
		&i.AfterLabel,
		&i.CtaText,
		&i.CtaUrl,
		&i.IsPublished,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessImages,
		&i.SpaceID,
		&i.Source,
		&i.UploadRequestID,
		&i.TenantID,
		&i.CreatedBy,
	)
	return i, err
}

const incrementViewCount = `-- name: IncrementViewCount :exec
UPDATE comparisons SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementViewCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementViewCount, id)
	return err
}

const listComparisonsBySpaceID = `-- name: ListComparisonsBySpaceID :many
SELECT id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by FROM comparisons WHERE space_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListComparisonsBySpaceID(ctx context.Context, spaceID pgtype.UUID) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listComparisonsBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Category,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.BeforeLabel,
			&i.AfterLabel,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublished,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessImages,
			&i.SpaceID,
			&i.Source,
			&i.UploadRequestID,
			&i.TenantID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComparisonsByTenantID = `-- name: ListComparisonsByTenantID :many
SELECT id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by FROM comparisons WHERE tenant_id = $1 ORDER BY created_at DESC
`

// Tenant-scoped queries
func (q *Queries) ListComparisonsByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listComparisonsByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Category,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.BeforeLabel,
			&i.AfterLabel,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublished,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessImages,
			&i.SpaceID,
			&i.Source,
			&i.UploadRequestID,
			&i.TenantID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComparisonsByUserID = `-- name: ListComparisonsByUserID :many
SELECT id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by FROM comparisons WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListComparisonsByUserID(ctx context.Context, userID string) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listComparisonsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Category,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.BeforeLabel,
			&i.AfterLabel,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublished,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessImages,
			&i.SpaceID,
			&i.Source,
			&i.UploadRequestID,
			&i.TenantID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComparisonsByUserIDs = `-- name: ListComparisonsByUserIDs :many
SELECT id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by FROM comparisons WHERE user_id = ANY($1::text[]) ORDER BY created_at DESC
`

func (q *Queries) ListComparisonsByUserIDs(ctx context.Context, dollar_1 []string) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listComparisonsByUserIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Category,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.BeforeLabel,
			&i.AfterLabel,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublished,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessImages,
			&i.SpaceID,
			&i.Source,
			&i.UploadRequestID,
			&i.TenantID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedComparisonsBySpaceID = `-- name: ListPublishedComparisonsBySpaceID :many
SELECT id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by FROM comparisons WHERE space_id = $1 AND is_published = true ORDER BY created_at DESC
`

func (q *Queries) ListPublishedComparisonsBySpaceID(ctx context.Context, spaceID pgtype.UUID) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listPublishedComparisonsBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Category,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.BeforeLabel,
			&i.AfterLabel,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublished,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessImages,
			&i.SpaceID,
			&i.Source,
			&i.UploadRequestID,
			&i.TenantID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedComparisonsByUserID = `-- name: ListPublishedComparisonsByUserID :many
SELECT id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by FROM comparisons WHERE user_id = $1 AND is_published = true ORDER BY created_at DESC
`

func (q *Queries) ListPublishedComparisonsByUserID(ctx context.Context, userID string) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listPublishedComparisonsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Category,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.BeforeLabel,
			&i.AfterLabel,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublished,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessImages,
			&i.SpaceID,
			&i.Source,
			&i.UploadRequestID,
			&i.TenantID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComparison = `-- name: UpdateComparison :one
UPDATE comparisons SET
    title = $2, description = $3, category = $4,
    before_image_url = $5, after_image_url = $6,
    before_label = $7, after_label = $8,
    cta_text = $9, cta_url = $10, is_published = $11, process_images = $12
WHERE id = $1 RETURNING id, user_id, brand_id, title, description, slug, category, before_image_url, after_image_url, before_label, after_label, cta_text, cta_url, is_published, view_count, created_at, updated_at, process_images, space_id, source, upload_request_id, tenant_id, created_by
`

type UpdateComparisonParams struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Category       ComparisonCategory `json:"category"`
	BeforeImageUrl string             `json:"before_image_url"`
	AfterImageUrl  string             `json:"after_image_url"`
	BeforeLabel    string             `json:"before_label"`
	AfterLabel     string             `json:"after_label"`
	CtaText        pgtype.Text        `json:"cta_text"`
	CtaUrl         pgtype.Text        `json:"cta_url"`
	IsPublished    bool               `json:"is_published"`
	ProcessImages  []byte             `json:"process_images"`
}

func (q *Queries) UpdateComparison(ctx context.Context, arg UpdateComparisonParams) (Comparison, error) {
	row := q.db.QueryRow(ctx, updateComparison,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.BeforeImageUrl,
		arg.AfterImageUrl,
		arg.BeforeLabel,
		arg.AfterLabel,
		arg.CtaText,
		arg.CtaUrl,
		arg.IsPublished,
		arg.ProcessImages,
	)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Category,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.BeforeLabel,
		&i.AfterLabel,
		&i.CtaText,
		&i.CtaUrl,
		&i.IsPublished,
		&i.ViewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessImages,
		&i.SpaceID,
		&i.Source,
		&i.UploadRequestID,
		&i.TenantID,
		&i.CreatedBy,
	)
	return i, err
}
