// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content_calendar.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContentCalendarEntry = `-- name: CreateContentCalendarEntry :one
INSERT INTO content_calendar (user_id, comparison_id, review_id, scheduled_date, content_type, platform, caption_template)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, comparison_id, review_id, scheduled_date, content_type, platform, caption_template, status, created_at
`

type CreateContentCalendarEntryParams struct {
	UserID          string          `json:"user_id"`
	ComparisonID    pgtype.UUID     `json:"comparison_id"`
	ReviewID        pgtype.UUID     `json:"review_id"`
	ScheduledDate   pgtype.Date     `json:"scheduled_date"`
	ContentType     ContentType     `json:"content_type"`
	Platform        ContentPlatform `json:"platform"`
	CaptionTemplate pgtype.Text     `json:"caption_template"`
}

func (q *Queries) CreateContentCalendarEntry(ctx context.Context, arg CreateContentCalendarEntryParams) (ContentCalendar, error) {
	row := q.db.QueryRow(ctx, createContentCalendarEntry,
		arg.UserID,
		arg.ComparisonID,
		arg.ReviewID,
		arg.ScheduledDate,
		arg.ContentType,
		arg.Platform,
		arg.CaptionTemplate,
	)
	var i ContentCalendar
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ComparisonID,
		&i.ReviewID,
		&i.ScheduledDate,
		&i.ContentType,
		&i.Platform,
		&i.CaptionTemplate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContentCalendarByDateRange = `-- name: DeleteContentCalendarByDateRange :exec
DELETE FROM content_calendar WHERE user_id = $1 AND scheduled_date >= $2 AND scheduled_date <= $3
`

type DeleteContentCalendarByDateRangeParams struct {
	UserID          string      `json:"user_id"`
	ScheduledDate   pgtype.Date `json:"scheduled_date"`
	ScheduledDate_2 pgtype.Date `json:"scheduled_date_2"`
}

func (q *Queries) DeleteContentCalendarByDateRange(ctx context.Context, arg DeleteContentCalendarByDateRangeParams) error {
	_, err := q.db.Exec(ctx, deleteContentCalendarByDateRange, arg.UserID, arg.ScheduledDate, arg.ScheduledDate_2)
	return err
}

const getContentCalendarSettings = `-- name: GetContentCalendarSettings :one
SELECT id, user_id, weekly_frequency, preferred_platforms, preferred_content_types, created_at, updated_at FROM content_calendar_settings WHERE user_id = $1
`

func (q *Queries) GetContentCalendarSettings(ctx context.Context, userID string) (ContentCalendarSetting, error) {
	row := q.db.QueryRow(ctx, getContentCalendarSettings, userID)
	var i ContentCalendarSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeeklyFrequency,
		&i.PreferredPlatforms,
		&i.PreferredContentTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContentCalendarByDateRange = `-- name: ListContentCalendarByDateRange :many
SELECT id, user_id, comparison_id, review_id, scheduled_date, content_type, platform, caption_template, status, created_at FROM content_calendar WHERE user_id = $1 AND scheduled_date >= $2 AND scheduled_date <= $3
ORDER BY scheduled_date ASC, created_at ASC
`

type ListContentCalendarByDateRangeParams struct {
	UserID          string      `json:"user_id"`
	ScheduledDate   pgtype.Date `json:"scheduled_date"`
	ScheduledDate_2 pgtype.Date `json:"scheduled_date_2"`
}

func (q *Queries) ListContentCalendarByDateRange(ctx context.Context, arg ListContentCalendarByDateRangeParams) ([]ContentCalendar, error) {
	rows, err := q.db.Query(ctx, listContentCalendarByDateRange, arg.UserID, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentCalendar{}
	for rows.Next() {
		var i ContentCalendar
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ComparisonID,
			&i.ReviewID,
			&i.ScheduledDate,
			&i.ContentType,
			&i.Platform,
			&i.CaptionTemplate,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentCalendarStatus = `-- name: UpdateContentCalendarStatus :exec
UPDATE content_calendar SET status = $2 WHERE id = $1
`

type UpdateContentCalendarStatusParams struct {
	ID     pgtype.UUID    `json:"id"`
	Status CalendarStatus `json:"status"`
}

func (q *Queries) UpdateContentCalendarStatus(ctx context.Context, arg UpdateContentCalendarStatusParams) error {
	_, err := q.db.Exec(ctx, updateContentCalendarStatus, arg.ID, arg.Status)
	return err
}

const upsertContentCalendarSettings = `-- name: UpsertContentCalendarSettings :one
INSERT INTO content_calendar_settings (user_id, weekly_frequency, preferred_platforms, preferred_content_types)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    weekly_frequency = EXCLUDED.weekly_frequency,
    preferred_platforms = EXCLUDED.preferred_platforms,
    preferred_content_types = EXCLUDED.preferred_content_types
RETURNING id, user_id, weekly_frequency, preferred_platforms, preferred_content_types, created_at, updated_at
`

type UpsertContentCalendarSettingsParams struct {
	UserID                string `json:"user_id"`
	WeeklyFrequency       int32  `json:"weekly_frequency"`
	PreferredPlatforms    []byte `json:"preferred_platforms"`
	PreferredContentTypes []byte `json:"preferred_content_types"`
}

func (q *Queries) UpsertContentCalendarSettings(ctx context.Context, arg UpsertContentCalendarSettingsParams) (ContentCalendarSetting, error) {
	row := q.db.QueryRow(ctx, upsertContentCalendarSettings,
		arg.UserID,
		arg.WeeklyFrequency,
		arg.PreferredPlatforms,
		arg.PreferredContentTypes,
	)
	var i ContentCalendarSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeeklyFrequency,
		&i.PreferredPlatforms,
		&i.PreferredContentTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
