// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: galleries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addComparisonToGallery = `-- name: AddComparisonToGallery :exec
INSERT INTO gallery_comparisons (gallery_id, comparison_id, sort_order)
VALUES ($1, $2, $3)
`

type AddComparisonToGalleryParams struct {
	GalleryID    pgtype.UUID `json:"gallery_id"`
	ComparisonID pgtype.UUID `json:"comparison_id"`
	SortOrder    int32       `json:"sort_order"`
}

func (q *Queries) AddComparisonToGallery(ctx context.Context, arg AddComparisonToGalleryParams) error {
	_, err := q.db.Exec(ctx, addComparisonToGallery, arg.GalleryID, arg.ComparisonID, arg.SortOrder)
	return err
}

const createGallery = `-- name: CreateGallery :one
INSERT INTO galleries (user_id, title, slug, description)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, title, slug, description, is_published, created_at, updated_at
`

type CreateGalleryParams struct {
	UserID      string      `json:"user_id"`
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateGallery(ctx context.Context, arg CreateGalleryParams) (Gallery, error) {
	row := q.db.QueryRow(ctx, createGallery,
		arg.UserID,
		arg.Title,
		arg.Slug,
		arg.Description,
	)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGallery = `-- name: DeleteGallery :exec
DELETE FROM galleries WHERE id = $1
`

func (q *Queries) DeleteGallery(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGallery, id)
	return err
}

const getGalleryByID = `-- name: GetGalleryByID :one
SELECT id, user_id, title, slug, description, is_published, created_at, updated_at FROM galleries WHERE id = $1
`

func (q *Queries) GetGalleryByID(ctx context.Context, id pgtype.UUID) (Gallery, error) {
	row := q.db.QueryRow(ctx, getGalleryByID, id)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGalleryBySlug = `-- name: GetGalleryBySlug :one
SELECT id, user_id, title, slug, description, is_published, created_at, updated_at FROM galleries WHERE slug = $1
`

func (q *Queries) GetGalleryBySlug(ctx context.Context, slug string) (Gallery, error) {
	row := q.db.QueryRow(ctx, getGalleryBySlug, slug)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGalleryComparisons = `-- name: GetGalleryComparisons :many
SELECT c.id, c.user_id, c.brand_id, c.title, c.description, c.slug, c.category, c.before_image_url, c.after_image_url, c.before_label, c.after_label, c.cta_text, c.cta_url, c.is_published, c.view_count, c.created_at, c.updated_at FROM comparisons c
JOIN gallery_comparisons gc ON gc.comparison_id = c.id
WHERE gc.gallery_id = $1
ORDER BY gc.sort_order
`

func (q *Queries) GetGalleryComparisons(ctx context.Context, galleryID pgtype.UUID) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, getGalleryComparisons, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Category,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.BeforeLabel,
			&i.AfterLabel,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublished,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGalleriesByUserID = `-- name: ListGalleriesByUserID :many
SELECT id, user_id, title, slug, description, is_published, created_at, updated_at FROM galleries WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGalleriesByUserID(ctx context.Context, userID string) ([]Gallery, error) {
	rows, err := q.db.Query(ctx, listGalleriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gallery{}
	for rows.Next() {
		var i Gallery
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGalleriesByUserIDs = `-- name: ListGalleriesByUserIDs :many
SELECT id, user_id, title, slug, description, is_published, created_at, updated_at FROM galleries WHERE user_id = ANY($1::text[]) ORDER BY created_at DESC
`

func (q *Queries) ListGalleriesByUserIDs(ctx context.Context, dollar_1 []string) ([]Gallery, error) {
	rows, err := q.db.Query(ctx, listGalleriesByUserIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gallery{}
	for rows.Next() {
		var i Gallery
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedGalleriesByUserID = `-- name: ListPublishedGalleriesByUserID :many
SELECT id, user_id, title, slug, description, is_published, created_at, updated_at FROM galleries WHERE user_id = $1 AND is_published = true ORDER BY created_at DESC
`

func (q *Queries) ListPublishedGalleriesByUserID(ctx context.Context, userID string) ([]Gallery, error) {
	rows, err := q.db.Query(ctx, listPublishedGalleriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gallery{}
	for rows.Next() {
		var i Gallery
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeComparisonFromGallery = `-- name: RemoveComparisonFromGallery :exec
DELETE FROM gallery_comparisons WHERE gallery_id = $1 AND comparison_id = $2
`

type RemoveComparisonFromGalleryParams struct {
	GalleryID    pgtype.UUID `json:"gallery_id"`
	ComparisonID pgtype.UUID `json:"comparison_id"`
}

func (q *Queries) RemoveComparisonFromGallery(ctx context.Context, arg RemoveComparisonFromGalleryParams) error {
	_, err := q.db.Exec(ctx, removeComparisonFromGallery, arg.GalleryID, arg.ComparisonID)
	return err
}

const updateGallery = `-- name: UpdateGallery :one
UPDATE galleries SET title = $2, description = $3, is_published = $4
WHERE id = $1 RETURNING id, user_id, title, slug, description, is_published, created_at, updated_at
`

type UpdateGalleryParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsPublished bool        `json:"is_published"`
}

func (q *Queries) UpdateGallery(ctx context.Context, arg UpdateGalleryParams) (Gallery, error) {
	row := q.db.QueryRow(ctx, updateGallery,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsPublished,
	)
	var i Gallery
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
