// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyticsEventType string

const (
	AnalyticsEventTypeView           AnalyticsEventType = "view"
	AnalyticsEventTypeSliderInteract AnalyticsEventType = "slider_interact"
	AnalyticsEventTypeCtaClick       AnalyticsEventType = "cta_click"
	AnalyticsEventTypeShare          AnalyticsEventType = "share"
)

func (e *AnalyticsEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalyticsEventType(s)
	case string:
		*e = AnalyticsEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalyticsEventType: %T", src)
	}
	return nil
}

type NullAnalyticsEventType struct {
	AnalyticsEventType AnalyticsEventType `json:"analytics_event_type"`
	Valid              bool               `json:"valid"` // Valid is true if AnalyticsEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalyticsEventType) Scan(value interface{}) error {
	if value == nil {
		ns.AnalyticsEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalyticsEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalyticsEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalyticsEventType), nil
}

type BenchmarkMetric string

const (
	BenchmarkMetricAvgViews         BenchmarkMetric = "avg_views"
	BenchmarkMetricAvgRating        BenchmarkMetric = "avg_rating"
	BenchmarkMetricConversionRate   BenchmarkMetric = "conversion_rate"
	BenchmarkMetricComparisonsCount BenchmarkMetric = "comparisons_count"
)

func (e *BenchmarkMetric) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BenchmarkMetric(s)
	case string:
		*e = BenchmarkMetric(s)
	default:
		return fmt.Errorf("unsupported scan type for BenchmarkMetric: %T", src)
	}
	return nil
}

type NullBenchmarkMetric struct {
	BenchmarkMetric BenchmarkMetric `json:"benchmark_metric"`
	Valid           bool            `json:"valid"` // Valid is true if BenchmarkMetric is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBenchmarkMetric) Scan(value interface{}) error {
	if value == nil {
		ns.BenchmarkMetric, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BenchmarkMetric.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBenchmarkMetric) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BenchmarkMetric), nil
}

type CalendarStatus string

const (
	CalendarStatusScheduled CalendarStatus = "scheduled"
	CalendarStatusPublished CalendarStatus = "published"
	CalendarStatusSkipped   CalendarStatus = "skipped"
)

func (e *CalendarStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CalendarStatus(s)
	case string:
		*e = CalendarStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CalendarStatus: %T", src)
	}
	return nil
}

type NullCalendarStatus struct {
	CalendarStatus CalendarStatus `json:"calendar_status"`
	Valid          bool           `json:"valid"` // Valid is true if CalendarStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCalendarStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CalendarStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CalendarStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCalendarStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CalendarStatus), nil
}

type ComparisonCategory string

const (
	ComparisonCategoryBeauty     ComparisonCategory = "beauty"
	ComparisonCategoryFitness    ComparisonCategory = "fitness"
	ComparisonCategoryDental     ComparisonCategory = "dental"
	ComparisonCategoryRenovation ComparisonCategory = "renovation"
	ComparisonCategoryOther      ComparisonCategory = "other"
)

func (e *ComparisonCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComparisonCategory(s)
	case string:
		*e = ComparisonCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ComparisonCategory: %T", src)
	}
	return nil
}

type NullComparisonCategory struct {
	ComparisonCategory ComparisonCategory `json:"comparison_category"`
	Valid              bool               `json:"valid"` // Valid is true if ComparisonCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComparisonCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ComparisonCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComparisonCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComparisonCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComparisonCategory), nil
}

type ComparisonSource string

const (
	ComparisonSourceMerchant ComparisonSource = "merchant"
	ComparisonSourceClient   ComparisonSource = "client"
)

func (e *ComparisonSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComparisonSource(s)
	case string:
		*e = ComparisonSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ComparisonSource: %T", src)
	}
	return nil
}

type NullComparisonSource struct {
	ComparisonSource ComparisonSource `json:"comparison_source"`
	Valid            bool             `json:"valid"` // Valid is true if ComparisonSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComparisonSource) Scan(value interface{}) error {
	if value == nil {
		ns.ComparisonSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComparisonSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComparisonSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComparisonSource), nil
}

type ContentPlatform string

const (
	ContentPlatformInstagram ContentPlatform = "instagram"
	ContentPlatformFacebook  ContentPlatform = "facebook"
	ContentPlatformTiktok    ContentPlatform = "tiktok"
	ContentPlatformTwitter   ContentPlatform = "twitter"
)

func (e *ContentPlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentPlatform(s)
	case string:
		*e = ContentPlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentPlatform: %T", src)
	}
	return nil
}

type NullContentPlatform struct {
	ContentPlatform ContentPlatform `json:"content_platform"`
	Valid           bool            `json:"valid"` // Valid is true if ContentPlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentPlatform) Scan(value interface{}) error {
	if value == nil {
		ns.ContentPlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentPlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentPlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentPlatform), nil
}

type ContentType string

const (
	ContentTypeBeforeAfter ContentType = "before_after"
	ContentTypeReviewQuote ContentType = "review_quote"
	ContentTypeTimeline    ContentType = "timeline"
	ContentTypeTip         ContentType = "tip"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"content_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type CtaType string

const (
	CtaTypeLink   CtaType = "link"
	CtaTypeButton CtaType = "button"
	CtaTypeNone   CtaType = "none"
)

func (e *CtaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CtaType(s)
	case string:
		*e = CtaType(s)
	default:
		return fmt.Errorf("unsupported scan type for CtaType: %T", src)
	}
	return nil
}

type NullCtaType struct {
	CtaType CtaType `json:"cta_type"`
	Valid   bool    `json:"valid"` // Valid is true if CtaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCtaType) Scan(value interface{}) error {
	if value == nil {
		ns.CtaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CtaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCtaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CtaType), nil
}

type DeviceType string

const (
	DeviceTypeDesktop DeviceType = "desktop"
	DeviceTypeMobile  DeviceType = "mobile"
	DeviceTypeTablet  DeviceType = "tablet"
)

func (e *DeviceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceType(s)
	case string:
		*e = DeviceType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceType: %T", src)
	}
	return nil
}

type NullDeviceType struct {
	DeviceType DeviceType `json:"device_type"`
	Valid      bool       `json:"valid"` // Valid is true if DeviceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceType) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceType), nil
}

type FormType string

const (
	FormTypeContact FormType = "contact"
	FormTypeBooking FormType = "booking"
	FormTypeBoth    FormType = "both"
)

func (e *FormType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FormType(s)
	case string:
		*e = FormType(s)
	default:
		return fmt.Errorf("unsupported scan type for FormType: %T", src)
	}
	return nil
}

type NullFormType struct {
	FormType FormType `json:"form_type"`
	Valid    bool     `json:"valid"` // Valid is true if FormType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFormType) Scan(value interface{}) error {
	if value == nil {
		ns.FormType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FormType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFormType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FormType), nil
}

type LeadStatus string

const (
	LeadStatusNew       LeadStatus = "new"
	LeadStatusContacted LeadStatus = "contacted"
	LeadStatusBooked    LeadStatus = "booked"
	LeadStatusCompleted LeadStatus = "completed"
	LeadStatusCancelled LeadStatus = "cancelled"
)

func (e *LeadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeadStatus(s)
	case string:
		*e = LeadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LeadStatus: %T", src)
	}
	return nil
}

type NullLeadStatus struct {
	LeadStatus LeadStatus `json:"lead_status"`
	Valid      bool       `json:"valid"` // Valid is true if LeadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LeadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeadStatus), nil
}

type LeadType string

const (
	LeadTypeContact LeadType = "contact"
	LeadTypeBooking LeadType = "booking"
)

func (e *LeadType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeadType(s)
	case string:
		*e = LeadType(s)
	default:
		return fmt.Errorf("unsupported scan type for LeadType: %T", src)
	}
	return nil
}

type NullLeadType struct {
	LeadType LeadType `json:"lead_type"`
	Valid    bool     `json:"valid"` // Valid is true if LeadType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeadType) Scan(value interface{}) error {
	if value == nil {
		ns.LeadType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeadType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeadType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeadType), nil
}

type ReviewStatus string

const (
	ReviewStatusPending   ReviewStatus = "pending"
	ReviewStatusPublished ReviewStatus = "published"
	ReviewStatusHidden    ReviewStatus = "hidden"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus `json:"review_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type TeamRole string

const (
	TeamRoleOwner  TeamRole = "owner"
	TeamRoleAdmin  TeamRole = "admin"
	TeamRoleMember TeamRole = "member"
)

func (e *TeamRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamRole(s)
	case string:
		*e = TeamRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamRole: %T", src)
	}
	return nil
}

type NullTeamRole struct {
	TeamRole TeamRole `json:"team_role"`
	Valid    bool     `json:"valid"` // Valid is true if TeamRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamRole) Scan(value interface{}) error {
	if value == nil {
		ns.TeamRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamRole), nil
}

type UploadRequestSentVia string

const (
	UploadRequestSentViaEmail      UploadRequestSentVia = "email"
	UploadRequestSentViaSms        UploadRequestSentVia = "sms"
	UploadRequestSentViaManualLink UploadRequestSentVia = "manual_link"
)

func (e *UploadRequestSentVia) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadRequestSentVia(s)
	case string:
		*e = UploadRequestSentVia(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadRequestSentVia: %T", src)
	}
	return nil
}

type NullUploadRequestSentVia struct {
	UploadRequestSentVia UploadRequestSentVia `json:"upload_request_sent_via"`
	Valid                bool                 `json:"valid"` // Valid is true if UploadRequestSentVia is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadRequestSentVia) Scan(value interface{}) error {
	if value == nil {
		ns.UploadRequestSentVia, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadRequestSentVia.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadRequestSentVia) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadRequestSentVia), nil
}

type UploadRequestStatus string

const (
	UploadRequestStatusSent      UploadRequestStatus = "sent"
	UploadRequestStatusOpened    UploadRequestStatus = "opened"
	UploadRequestStatusSubmitted UploadRequestStatus = "submitted"
	UploadRequestStatusApproved  UploadRequestStatus = "approved"
	UploadRequestStatusRejected  UploadRequestStatus = "rejected"
	UploadRequestStatusExpired   UploadRequestStatus = "expired"
)

func (e *UploadRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadRequestStatus(s)
	case string:
		*e = UploadRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadRequestStatus: %T", src)
	}
	return nil
}

type NullUploadRequestStatus struct {
	UploadRequestStatus UploadRequestStatus `json:"upload_request_status"`
	Valid               bool                `json:"valid"` // Valid is true if UploadRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UploadRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadRequestStatus), nil
}

type UploadRequestType string

const (
	UploadRequestTypeBeforeOnly UploadRequestType = "before_only"
	UploadRequestTypeAfterOnly  UploadRequestType = "after_only"
	UploadRequestTypeBoth       UploadRequestType = "both"
)

func (e *UploadRequestType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadRequestType(s)
	case string:
		*e = UploadRequestType(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadRequestType: %T", src)
	}
	return nil
}

type NullUploadRequestType struct {
	UploadRequestType UploadRequestType `json:"upload_request_type"`
	Valid             bool              `json:"valid"` // Valid is true if UploadRequestType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadRequestType) Scan(value interface{}) error {
	if value == nil {
		ns.UploadRequestType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadRequestType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadRequestType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadRequestType), nil
}

type UserPlan string

const (
	UserPlanFree     UserPlan = "free"
	UserPlanPro      UserPlan = "pro"
	UserPlanBusiness UserPlan = "business"
)

func (e *UserPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserPlan(s)
	case string:
		*e = UserPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for UserPlan: %T", src)
	}
	return nil
}

type NullUserPlan struct {
	UserPlan UserPlan `json:"user_plan"`
	Valid    bool     `json:"valid"` // Valid is true if UserPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserPlan) Scan(value interface{}) error {
	if value == nil {
		ns.UserPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserPlan), nil
}

type Achievement struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     string             `json:"user_id"`
	Type       string             `json:"type"`
	AchievedAt pgtype.Timestamptz `json:"achieved_at"`
}

type Analytic struct {
	ID           pgtype.UUID        `json:"id"`
	ComparisonID pgtype.UUID        `json:"comparison_id"`
	EventType    AnalyticsEventType `json:"event_type"`
	Device       NullDeviceType     `json:"device"`
	Referrer     pgtype.Text        `json:"referrer"`
	Country      pgtype.Text        `json:"country"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Brand struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         string             `json:"user_id"`
	Name           string             `json:"name"`
	LogoUrl        pgtype.Text        `json:"logo_url"`
	PrimaryColor   string             `json:"primary_color"`
	SecondaryColor string             `json:"secondary_color"`
	WebsiteUrl     pgtype.Text        `json:"website_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Comparison struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          string             `json:"user_id"`
	BrandID         pgtype.UUID        `json:"brand_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Slug            string             `json:"slug"`
	Category        ComparisonCategory `json:"category"`
	BeforeImageUrl  string             `json:"before_image_url"`
	AfterImageUrl   string             `json:"after_image_url"`
	BeforeLabel     string             `json:"before_label"`
	AfterLabel      string             `json:"after_label"`
	CtaText         pgtype.Text        `json:"cta_text"`
	CtaUrl          pgtype.Text        `json:"cta_url"`
	IsPublished     bool               `json:"is_published"`
	ViewCount       int32              `json:"view_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProcessImages   []byte             `json:"process_images"`
	SpaceID         pgtype.UUID        `json:"space_id"`
	Source          ComparisonSource   `json:"source"`
	UploadRequestID pgtype.UUID        `json:"upload_request_id"`
}

type ContentCalendar struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          string             `json:"user_id"`
	ComparisonID    pgtype.UUID        `json:"comparison_id"`
	ReviewID        pgtype.UUID        `json:"review_id"`
	ScheduledDate   pgtype.Date        `json:"scheduled_date"`
	ContentType     ContentType        `json:"content_type"`
	Platform        ContentPlatform    `json:"platform"`
	CaptionTemplate pgtype.Text        `json:"caption_template"`
	Status          CalendarStatus     `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ContentCalendarSetting struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                string             `json:"user_id"`
	WeeklyFrequency       int32              `json:"weekly_frequency"`
	PreferredPlatforms    []byte             `json:"preferred_platforms"`
	PreferredContentTypes []byte             `json:"preferred_content_types"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type FormConfig struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           string             `json:"user_id"`
	FormType         FormType           `json:"form_type"`
	Services         []byte             `json:"services"`
	WhatsappNumber   pgtype.Text        `json:"whatsapp_number"`
	AutoReplyMessage pgtype.Text        `json:"auto_reply_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Gallery struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	IsPublished bool               `json:"is_published"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GalleryComparison struct {
	GalleryID    pgtype.UUID `json:"gallery_id"`
	ComparisonID pgtype.UUID `json:"comparison_id"`
	SortOrder    int32       `json:"sort_order"`
}

type IndustryBenchmark struct {
	ID           pgtype.UUID        `json:"id"`
	Category     string             `json:"category"`
	Metric       BenchmarkMetric    `json:"metric"`
	Value        float64            `json:"value"`
	SampleSize   int32              `json:"sample_size"`
	Percentiles  []byte             `json:"percentiles"`
	CalculatedAt pgtype.Timestamptz `json:"calculated_at"`
}

type Lead struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        string             `json:"user_id"`
	ComparisonID  pgtype.UUID        `json:"comparison_id"`
	SpaceID       pgtype.UUID        `json:"space_id"`
	Type          LeadType           `json:"type"`
	Name          string             `json:"name"`
	Phone         pgtype.Text        `json:"phone"`
	Email         pgtype.Text        `json:"email"`
	Service       pgtype.Text        `json:"service"`
	PreferredDate pgtype.Text        `json:"preferred_date"`
	PreferredTime pgtype.Text        `json:"preferred_time"`
	Message       pgtype.Text        `json:"message"`
	Status        LeadStatus         `json:"status"`
	SourceUrl     pgtype.Text        `json:"source_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Review struct {
	ID               pgtype.UUID        `json:"id"`
	ComparisonID     pgtype.UUID        `json:"comparison_id"`
	SpaceID          pgtype.UUID        `json:"space_id"`
	UserID           string             `json:"user_id"`
	ReviewerName     string             `json:"reviewer_name"`
	ReviewerPhotoUrl pgtype.Text        `json:"reviewer_photo_url"`
	ReviewerContact  pgtype.Text        `json:"reviewer_contact"`
	Rating           int32              `json:"rating"`
	Content          string             `json:"content"`
	Reply            pgtype.Text        `json:"reply"`
	ReplyAt          pgtype.Timestamptz `json:"reply_at"`
	Status           ReviewStatus       `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Space struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        string             `json:"user_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Category      ComparisonCategory `json:"category"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	Services      []byte             `json:"services"`
	CtaText       pgtype.Text        `json:"cta_text"`
	CtaUrl        pgtype.Text        `json:"cta_url"`
	CtaType       CtaType            `json:"cta_type"`
	IsPublic      bool               `json:"is_public"`
	Subdomain     pgtype.Text        `json:"subdomain"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	TeamOwnerID string             `json:"team_owner_id"`
	Role        TeamRole           `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Timeline struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	SpaceID     pgtype.UUID        `json:"space_id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Category    pgtype.Text        `json:"category"`
	CtaText     pgtype.Text        `json:"cta_text"`
	CtaUrl      pgtype.Text        `json:"cta_url"`
	IsPublic    bool               `json:"is_public"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TimelineEntry struct {
	ID         pgtype.UUID        `json:"id"`
	TimelineID pgtype.UUID        `json:"timeline_id"`
	ImageUrl   string             `json:"image_url"`
	Label      string             `json:"label"`
	Date       pgtype.Date        `json:"date"`
	Note       pgtype.Text        `json:"note"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type UploadRequest struct {
	ID              pgtype.UUID          `json:"id"`
	SpaceID         pgtype.UUID          `json:"space_id"`
	UserID          string               `json:"user_id"`
	Token           string               `json:"token"`
	ClientName      pgtype.Text          `json:"client_name"`
	ClientEmail     pgtype.Text          `json:"client_email"`
	ClientPhone     pgtype.Text          `json:"client_phone"`
	RequestType     UploadRequestType    `json:"request_type"`
	InstructionNote pgtype.Text          `json:"instruction_note"`
	BeforeImageUrl  pgtype.Text          `json:"before_image_url"`
	AfterImageUrl   pgtype.Text          `json:"after_image_url"`
	ReviewRating    pgtype.Int4          `json:"review_rating"`
	ReviewContent   pgtype.Text          `json:"review_content"`
	ServiceType     pgtype.Text          `json:"service_type"`
	Status          UploadRequestStatus  `json:"status"`
	SentVia         UploadRequestSentVia `json:"sent_via"`
	ReminderSentAt  pgtype.Timestamptz   `json:"reminder_sent_at"`
	SubmittedAt     pgtype.Timestamptz   `json:"submitted_at"`
	ReviewedAt      pgtype.Timestamptz   `json:"reviewed_at"`
	ExpiresAt       pgtype.Timestamptz   `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz   `json:"updated_at"`
}

type User struct {
	ID               string             `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	Plan             UserPlan           `json:"plan"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CustomSubdomain  pgtype.Text        `json:"custom_subdomain"`
	ApiKey           pgtype.Text        `json:"api_key"`
}
