// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnalyticsEventType string

const (
	AnalyticsEventTypeView           AnalyticsEventType = "view"
	AnalyticsEventTypeSliderInteract AnalyticsEventType = "slider_interact"
	AnalyticsEventTypeCtaClick       AnalyticsEventType = "cta_click"
	AnalyticsEventTypeShare          AnalyticsEventType = "share"
)

func (e *AnalyticsEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalyticsEventType(s)
	case string:
		*e = AnalyticsEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalyticsEventType: %T", src)
	}
	return nil
}

type NullAnalyticsEventType struct {
	AnalyticsEventType AnalyticsEventType `json:"analytics_event_type"`
	Valid              bool               `json:"valid"` // Valid is true if AnalyticsEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalyticsEventType) Scan(value interface{}) error {
	if value == nil {
		ns.AnalyticsEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalyticsEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalyticsEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalyticsEventType), nil
}

type ComparisonCategory string

const (
	ComparisonCategoryBeauty     ComparisonCategory = "beauty"
	ComparisonCategoryFitness    ComparisonCategory = "fitness"
	ComparisonCategoryDental     ComparisonCategory = "dental"
	ComparisonCategoryRenovation ComparisonCategory = "renovation"
	ComparisonCategoryOther      ComparisonCategory = "other"
)

func (e *ComparisonCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComparisonCategory(s)
	case string:
		*e = ComparisonCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ComparisonCategory: %T", src)
	}
	return nil
}

type NullComparisonCategory struct {
	ComparisonCategory ComparisonCategory `json:"comparison_category"`
	Valid              bool               `json:"valid"` // Valid is true if ComparisonCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComparisonCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ComparisonCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComparisonCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComparisonCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComparisonCategory), nil
}

type DeviceType string

const (
	DeviceTypeDesktop DeviceType = "desktop"
	DeviceTypeMobile  DeviceType = "mobile"
	DeviceTypeTablet  DeviceType = "tablet"
)

func (e *DeviceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceType(s)
	case string:
		*e = DeviceType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceType: %T", src)
	}
	return nil
}

type NullDeviceType struct {
	DeviceType DeviceType `json:"device_type"`
	Valid      bool       `json:"valid"` // Valid is true if DeviceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceType) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceType), nil
}

type TeamRole string

const (
	TeamRoleOwner  TeamRole = "owner"
	TeamRoleAdmin  TeamRole = "admin"
	TeamRoleMember TeamRole = "member"
)

func (e *TeamRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamRole(s)
	case string:
		*e = TeamRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamRole: %T", src)
	}
	return nil
}

type NullTeamRole struct {
	TeamRole TeamRole `json:"team_role"`
	Valid    bool     `json:"valid"` // Valid is true if TeamRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamRole) Scan(value interface{}) error {
	if value == nil {
		ns.TeamRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamRole), nil
}

type UserPlan string

const (
	UserPlanFree     UserPlan = "free"
	UserPlanPro      UserPlan = "pro"
	UserPlanBusiness UserPlan = "business"
)

func (e *UserPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserPlan(s)
	case string:
		*e = UserPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for UserPlan: %T", src)
	}
	return nil
}

type NullUserPlan struct {
	UserPlan UserPlan `json:"user_plan"`
	Valid    bool     `json:"valid"` // Valid is true if UserPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserPlan) Scan(value interface{}) error {
	if value == nil {
		ns.UserPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserPlan), nil
}

type Analytic struct {
	ID           pgtype.UUID        `json:"id"`
	ComparisonID pgtype.UUID        `json:"comparison_id"`
	EventType    AnalyticsEventType `json:"event_type"`
	Device       NullDeviceType     `json:"device"`
	Referrer     pgtype.Text        `json:"referrer"`
	Country      pgtype.Text        `json:"country"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Brand struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         string             `json:"user_id"`
	Name           string             `json:"name"`
	LogoUrl        pgtype.Text        `json:"logo_url"`
	PrimaryColor   string             `json:"primary_color"`
	SecondaryColor string             `json:"secondary_color"`
	WebsiteUrl     pgtype.Text        `json:"website_url"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Comparison struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         string             `json:"user_id"`
	BrandID        pgtype.UUID        `json:"brand_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Slug           string             `json:"slug"`
	Category       ComparisonCategory `json:"category"`
	BeforeImageUrl string             `json:"before_image_url"`
	AfterImageUrl  string             `json:"after_image_url"`
	BeforeLabel    string             `json:"before_label"`
	AfterLabel     string             `json:"after_label"`
	CtaText        pgtype.Text        `json:"cta_text"`
	CtaUrl         pgtype.Text        `json:"cta_url"`
	IsPublished    bool               `json:"is_published"`
	ViewCount      int32              `json:"view_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Gallery struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	IsPublished bool               `json:"is_published"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GalleryComparison struct {
	GalleryID    pgtype.UUID `json:"gallery_id"`
	ComparisonID pgtype.UUID `json:"comparison_id"`
	SortOrder    int32       `json:"sort_order"`
}

type TeamMember struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	TeamOwnerID string             `json:"team_owner_id"`
	Role        TeamRole           `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID               string             `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	Plan             UserPlan           `json:"plan"`
	StripeCustomerID pgtype.Text        `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CustomSubdomain  pgtype.Text        `json:"custom_subdomain"`
}
