// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReviewsByUserID = `-- name: CountReviewsByUserID :one
SELECT COUNT(*) FROM reviews WHERE user_id = $1
`

func (q *Queries) CountReviewsByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (comparison_id, space_id, user_id, reviewer_name, reviewer_photo_url, reviewer_contact, rating, content)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, comparison_id, space_id, user_id, reviewer_name, reviewer_photo_url, reviewer_contact, rating, content, reply, reply_at, status, created_at, updated_at
`

type CreateReviewParams struct {
	ComparisonID     pgtype.UUID `json:"comparison_id"`
	SpaceID          pgtype.UUID `json:"space_id"`
	UserID           string      `json:"user_id"`
	ReviewerName     string      `json:"reviewer_name"`
	ReviewerPhotoUrl pgtype.Text `json:"reviewer_photo_url"`
	ReviewerContact  pgtype.Text `json:"reviewer_contact"`
	Rating           int32       `json:"rating"`
	Content          string      `json:"content"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ComparisonID,
		arg.SpaceID,
		arg.UserID,
		arg.ReviewerName,
		arg.ReviewerPhotoUrl,
		arg.ReviewerContact,
		arg.Rating,
		arg.Content,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ComparisonID,
		&i.SpaceID,
		&i.UserID,
		&i.ReviewerName,
		&i.ReviewerPhotoUrl,
		&i.ReviewerContact,
		&i.Rating,
		&i.Content,
		&i.Reply,
		&i.ReplyAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, comparison_id, space_id, user_id, reviewer_name, reviewer_photo_url, reviewer_contact, rating, content, reply, reply_at, status, created_at, updated_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id pgtype.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ComparisonID,
		&i.SpaceID,
		&i.UserID,
		&i.ReviewerName,
		&i.ReviewerPhotoUrl,
		&i.ReviewerContact,
		&i.Rating,
		&i.Content,
		&i.Reply,
		&i.ReplyAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewStats = `-- name: GetReviewStats :one
SELECT COUNT(*) AS total, COALESCE(AVG(rating), 0)::float AS avg_rating,
       COUNT(*) FILTER (WHERE status = 'published') AS published_count
FROM reviews WHERE user_id = $1
`

type GetReviewStatsRow struct {
	Total          int64   `json:"total"`
	AvgRating      float64 `json:"avg_rating"`
	PublishedCount int64   `json:"published_count"`
}

func (q *Queries) GetReviewStats(ctx context.Context, userID string) (GetReviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getReviewStats, userID)
	var i GetReviewStatsRow
	err := row.Scan(&i.Total, &i.AvgRating, &i.PublishedCount)
	return i, err
}

const listPublishedReviewsByUserID = `-- name: ListPublishedReviewsByUserID :many
SELECT id, comparison_id, space_id, user_id, reviewer_name, reviewer_photo_url, reviewer_contact, rating, content, reply, reply_at, status, created_at, updated_at FROM reviews WHERE user_id = $1 AND status = 'published' ORDER BY created_at DESC LIMIT $2
`

type ListPublishedReviewsByUserIDParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListPublishedReviewsByUserID(ctx context.Context, arg ListPublishedReviewsByUserIDParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listPublishedReviewsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ComparisonID,
			&i.SpaceID,
			&i.UserID,
			&i.ReviewerName,
			&i.ReviewerPhotoUrl,
			&i.ReviewerContact,
			&i.Rating,
			&i.Content,
			&i.Reply,
			&i.ReplyAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUserIDs = `-- name: ListReviewsByUserIDs :many
SELECT id, comparison_id, space_id, user_id, reviewer_name, reviewer_photo_url, reviewer_contact, rating, content, reply, reply_at, status, created_at, updated_at FROM reviews WHERE user_id = ANY($1::text[]) ORDER BY created_at DESC
`

func (q *Queries) ListReviewsByUserIDs(ctx context.Context, dollar_1 []string) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByUserIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ComparisonID,
			&i.SpaceID,
			&i.UserID,
			&i.ReviewerName,
			&i.ReviewerPhotoUrl,
			&i.ReviewerContact,
			&i.Rating,
			&i.Content,
			&i.Reply,
			&i.ReplyAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewReply = `-- name: UpdateReviewReply :exec
UPDATE reviews SET reply = $2, reply_at = now() WHERE id = $1
`

type UpdateReviewReplyParams struct {
	ID    pgtype.UUID `json:"id"`
	Reply pgtype.Text `json:"reply"`
}

func (q *Queries) UpdateReviewReply(ctx context.Context, arg UpdateReviewReplyParams) error {
	_, err := q.db.Exec(ctx, updateReviewReply, arg.ID, arg.Reply)
	return err
}

const updateReviewStatus = `-- name: UpdateReviewStatus :exec
UPDATE reviews SET status = $2 WHERE id = $1
`

type UpdateReviewStatusParams struct {
	ID     pgtype.UUID  `json:"id"`
	Status ReviewStatus `json:"status"`
}

func (q *Queries) UpdateReviewStatus(ctx context.Context, arg UpdateReviewStatusParams) error {
	_, err := q.db.Exec(ctx, updateReviewStatus, arg.ID, arg.Status)
	return err
}
