// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: space_comparisons.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addComparisonToSpace = `-- name: AddComparisonToSpace :exec
INSERT INTO space_comparisons (space_id, comparison_id, position)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddComparisonToSpaceParams struct {
	SpaceID      pgtype.UUID `json:"space_id"`
	ComparisonID pgtype.UUID `json:"comparison_id"`
	Position     int32       `json:"position"`
}

func (q *Queries) AddComparisonToSpace(ctx context.Context, arg AddComparisonToSpaceParams) error {
	_, err := q.db.Exec(ctx, addComparisonToSpace, arg.SpaceID, arg.ComparisonID, arg.Position)
	return err
}

const countComparisonsBySpaceID = `-- name: CountComparisonsBySpaceID :one
SELECT COUNT(*) FROM space_comparisons WHERE space_id = $1
`

func (q *Queries) CountComparisonsBySpaceID(ctx context.Context, spaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countComparisonsBySpaceID, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listComparisonsBySpaceID = `-- name: ListComparisonsBySpaceID :many
SELECT c.id, c.user_id, c.brand_id, c.title, c.description, c.slug, c.category, c.before_image_url, c.after_image_url, c.before_label, c.after_label, c.cta_text, c.cta_url, c.is_published, c.view_count, c.created_at, c.updated_at, c.process_images, c.source, c.upload_request_id, c.tenant_id, c.created_by FROM comparisons c
JOIN space_comparisons sc ON sc.comparison_id = c.id
WHERE sc.space_id = $1
ORDER BY sc.position ASC, sc.created_at ASC
`

func (q *Queries) ListComparisonsBySpaceID(ctx context.Context, spaceID pgtype.UUID) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listComparisonsBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Category,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.BeforeLabel,
			&i.AfterLabel,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublished,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessImages,
			&i.Source,
			&i.UploadRequestID,
			&i.TenantID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedComparisonsBySpaceID = `-- name: ListPublishedComparisonsBySpaceID :many
SELECT c.id, c.user_id, c.brand_id, c.title, c.description, c.slug, c.category, c.before_image_url, c.after_image_url, c.before_label, c.after_label, c.cta_text, c.cta_url, c.is_published, c.view_count, c.created_at, c.updated_at, c.process_images, c.source, c.upload_request_id, c.tenant_id, c.created_by FROM comparisons c
JOIN space_comparisons sc ON sc.comparison_id = c.id
WHERE sc.space_id = $1 AND c.is_published = true
ORDER BY sc.position ASC, sc.created_at ASC
`

func (q *Queries) ListPublishedComparisonsBySpaceID(ctx context.Context, spaceID pgtype.UUID) ([]Comparison, error) {
	rows, err := q.db.Query(ctx, listPublishedComparisonsBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comparison{}
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Category,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.BeforeLabel,
			&i.AfterLabel,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublished,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessImages,
			&i.Source,
			&i.UploadRequestID,
			&i.TenantID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceIDsForComparison = `-- name: ListSpaceIDsForComparison :many
SELECT space_id FROM space_comparisons WHERE comparison_id = $1
`

func (q *Queries) ListSpaceIDsForComparison(ctx context.Context, comparisonID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSpaceIDsForComparison, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var space_id pgtype.UUID
		if err := rows.Scan(&space_id); err != nil {
			return nil, err
		}
		items = append(items, space_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeComparisonFromSpace = `-- name: RemoveComparisonFromSpace :exec
DELETE FROM space_comparisons WHERE space_id = $1 AND comparison_id = $2
`

type RemoveComparisonFromSpaceParams struct {
	SpaceID      pgtype.UUID `json:"space_id"`
	ComparisonID pgtype.UUID `json:"comparison_id"`
}

func (q *Queries) RemoveComparisonFromSpace(ctx context.Context, arg RemoveComparisonFromSpaceParams) error {
	_, err := q.db.Exec(ctx, removeComparisonFromSpace, arg.SpaceID, arg.ComparisonID)
	return err
}
