// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSpacesByUserID = `-- name: CountSpacesByUserID :one
SELECT COUNT(*) FROM spaces WHERE user_id = $1
`

func (q *Queries) CountSpacesByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSpacesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (user_id, slug, name, description, category, cover_image_url, services, cta_text, cta_url, cta_type, is_public)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, slug, name, description, category, cover_image_url, services, cta_text, cta_url, cta_type, is_public, subdomain, created_at, updated_at
`

type CreateSpaceParams struct {
	UserID        string             `json:"user_id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Category      ComparisonCategory `json:"category"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	Services      []byte             `json:"services"`
	CtaText       pgtype.Text        `json:"cta_text"`
	CtaUrl        pgtype.Text        `json:"cta_url"`
	CtaType       CtaType            `json:"cta_type"`
	IsPublic      bool               `json:"is_public"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace,
		arg.UserID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.CoverImageUrl,
		arg.Services,
		arg.CtaText,
		arg.CtaUrl,
		arg.CtaType,
		arg.IsPublic,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CoverImageUrl,
		&i.Services,
		&i.CtaText,
		&i.CtaUrl,
		&i.CtaType,
		&i.IsPublic,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getPublicSpaceBySlug = `-- name: GetPublicSpaceBySlug :one
SELECT id, user_id, slug, name, description, category, cover_image_url, services, cta_text, cta_url, cta_type, is_public, subdomain, created_at, updated_at FROM spaces WHERE slug = $1 AND is_public = true
`

func (q *Queries) GetPublicSpaceBySlug(ctx context.Context, slug string) (Space, error) {
	row := q.db.QueryRow(ctx, getPublicSpaceBySlug, slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CoverImageUrl,
		&i.Services,
		&i.CtaText,
		&i.CtaUrl,
		&i.CtaType,
		&i.IsPublic,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, user_id, slug, name, description, category, cover_image_url, services, cta_text, cta_url, cta_type, is_public, subdomain, created_at, updated_at FROM spaces WHERE id = $1
`

func (q *Queries) GetSpaceByID(ctx context.Context, id pgtype.UUID) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CoverImageUrl,
		&i.Services,
		&i.CtaText,
		&i.CtaUrl,
		&i.CtaType,
		&i.IsPublic,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpaceBySlug = `-- name: GetSpaceBySlug :one
SELECT id, user_id, slug, name, description, category, cover_image_url, services, cta_text, cta_url, cta_type, is_public, subdomain, created_at, updated_at FROM spaces WHERE slug = $1
`

func (q *Queries) GetSpaceBySlug(ctx context.Context, slug string) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceBySlug, slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CoverImageUrl,
		&i.Services,
		&i.CtaText,
		&i.CtaUrl,
		&i.CtaType,
		&i.IsPublic,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpacesByUserID = `-- name: ListSpacesByUserID :many
SELECT id, user_id, slug, name, description, category, cover_image_url, services, cta_text, cta_url, cta_type, is_public, subdomain, created_at, updated_at FROM spaces WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSpacesByUserID(ctx context.Context, userID string) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CoverImageUrl,
			&i.Services,
			&i.CtaText,
			&i.CtaUrl,
			&i.CtaType,
			&i.IsPublic,
			&i.Subdomain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesByUserIDs = `-- name: ListSpacesByUserIDs :many
SELECT id, user_id, slug, name, description, category, cover_image_url, services, cta_text, cta_url, cta_type, is_public, subdomain, created_at, updated_at FROM spaces WHERE user_id = ANY($1::text[]) ORDER BY created_at DESC
`

func (q *Queries) ListSpacesByUserIDs(ctx context.Context, dollar_1 []string) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesByUserIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.CoverImageUrl,
			&i.Services,
			&i.CtaText,
			&i.CtaUrl,
			&i.CtaType,
			&i.IsPublic,
			&i.Subdomain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces SET
    name = $2, description = $3, category = $4, cover_image_url = $5,
    services = $6, cta_text = $7, cta_url = $8, cta_type = $9, is_public = $10
WHERE id = $1 RETURNING id, user_id, slug, name, description, category, cover_image_url, services, cta_text, cta_url, cta_type, is_public, subdomain, created_at, updated_at
`

type UpdateSpaceParams struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Category      ComparisonCategory `json:"category"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	Services      []byte             `json:"services"`
	CtaText       pgtype.Text        `json:"cta_text"`
	CtaUrl        pgtype.Text        `json:"cta_url"`
	CtaType       CtaType            `json:"cta_type"`
	IsPublic      bool               `json:"is_public"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.CoverImageUrl,
		arg.Services,
		arg.CtaText,
		arg.CtaUrl,
		arg.CtaType,
		arg.IsPublic,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.CoverImageUrl,
		&i.Services,
		&i.CtaText,
		&i.CtaUrl,
		&i.CtaType,
		&i.IsPublic,
		&i.Subdomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
