// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (user_id, team_owner_id, role)
VALUES ($1, $2, $3) RETURNING id, user_id, team_owner_id, role, created_at
`

type AddTeamMemberParams struct {
	UserID      string   `json:"user_id"`
	TeamOwnerID string   `json:"team_owner_id"`
	Role        TeamRole `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.UserID, arg.TeamOwnerID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamOwnerID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT id, user_id, team_owner_id, role, created_at FROM team_members WHERE id = $1
`

func (q *Queries) GetTeamMember(ctx context.Context, id pgtype.UUID) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, id)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamOwnerID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMemberByUserAndOwner = `-- name: GetTeamMemberByUserAndOwner :one
SELECT id, user_id, team_owner_id, role, created_at FROM team_members WHERE user_id = $1 AND team_owner_id = $2
`

type GetTeamMemberByUserAndOwnerParams struct {
	UserID      string `json:"user_id"`
	TeamOwnerID string `json:"team_owner_id"`
}

func (q *Queries) GetTeamMemberByUserAndOwner(ctx context.Context, arg GetTeamMemberByUserAndOwnerParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMemberByUserAndOwner, arg.UserID, arg.TeamOwnerID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamOwnerID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamOwnerIDs = `-- name: GetTeamOwnerIDs :many
SELECT team_owner_id FROM team_members WHERE user_id = $1
`

func (q *Queries) GetTeamOwnerIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getTeamOwnerIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var team_owner_id string
		if err := rows.Scan(&team_owner_id); err != nil {
			return nil, err
		}
		items = append(items, team_owner_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersByOwner = `-- name: ListTeamMembersByOwner :many
SELECT tm.id, tm.user_id, tm.team_owner_id, tm.role, tm.created_at,
       u.email as member_email, u.name as member_name
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_owner_id = $1
`

type ListTeamMembersByOwnerRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	TeamOwnerID string             `json:"team_owner_id"`
	Role        TeamRole           `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MemberEmail string             `json:"member_email"`
	MemberName  string             `json:"member_name"`
}

func (q *Queries) ListTeamMembersByOwner(ctx context.Context, teamOwnerID string) ([]ListTeamMembersByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersByOwner, teamOwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersByOwnerRow{}
	for rows.Next() {
		var i ListTeamMembersByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TeamOwnerID,
			&i.Role,
			&i.CreatedAt,
			&i.MemberEmail,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByUserID = `-- name: ListTeamsByUserID :many
SELECT tm.id, tm.user_id, tm.team_owner_id, tm.role, tm.created_at,
       u.email as owner_email, u.name as owner_name
FROM team_members tm
JOIN users u ON u.id = tm.team_owner_id
WHERE tm.user_id = $1
`

type ListTeamsByUserIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	TeamOwnerID string             `json:"team_owner_id"`
	Role        TeamRole           `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	OwnerEmail  string             `json:"owner_email"`
	OwnerName   string             `json:"owner_name"`
}

func (q *Queries) ListTeamsByUserID(ctx context.Context, userID string) ([]ListTeamsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listTeamsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsByUserIDRow{}
	for rows.Next() {
		var i ListTeamsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TeamOwnerID,
			&i.Role,
			&i.CreatedAt,
			&i.OwnerEmail,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE id = $1
`

func (q *Queries) RemoveTeamMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTeamMember, id)
	return err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :one
UPDATE team_members SET role = $2 WHERE id = $1 RETURNING id, user_id, team_owner_id, role, created_at
`

type UpdateTeamMemberRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role TeamRole    `json:"role"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateTeamMemberRole, arg.ID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamOwnerID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
