// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTenantInvite = `-- name: AcceptTenantInvite :exec
UPDATE tenant_invites SET status = 'accepted' WHERE id = $1
`

func (q *Queries) AcceptTenantInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, acceptTenantInvite, id)
	return err
}

const cancelTenantInvite = `-- name: CancelTenantInvite :exec
UPDATE tenant_invites SET status = 'cancelled' WHERE id = $1
`

func (q *Queries) CancelTenantInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelTenantInvite, id)
	return err
}

const countActiveTenantMembers = `-- name: CountActiveTenantMembers :one
SELECT COUNT(*) FROM tenant_members WHERE tenant_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveTenantMembers(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTenantMembers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, plan, owner_id)
VALUES ($1, $2, $3, $4) RETURNING id, name, slug, plan, stripe_customer_id, stripe_subscription_id, owner_id, created_at, updated_at
`

type CreateTenantParams struct {
	Name    string   `json:"name"`
	Slug    string   `json:"slug"`
	Plan    UserPlan `json:"plan"`
	OwnerID string   `json:"owner_id"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.OwnerID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantInvite = `-- name: CreateTenantInvite :one
INSERT INTO tenant_invites (tenant_id, email, role, token, invited_by)
VALUES ($1, $2, $3, $4, $5) RETURNING id, tenant_id, email, role, token, invited_by, status, expires_at, created_at
`

type CreateTenantInviteParams struct {
	TenantID  pgtype.UUID      `json:"tenant_id"`
	Email     string           `json:"email"`
	Role      TenantMemberRole `json:"role"`
	Token     string           `json:"token"`
	InvitedBy string           `json:"invited_by"`
}

func (q *Queries) CreateTenantInvite(ctx context.Context, arg CreateTenantInviteParams) (TenantInvite, error) {
	row := q.db.QueryRow(ctx, createTenantInvite,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
	)
	var i TenantInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTenantMember = `-- name: CreateTenantMember :one
INSERT INTO tenant_members (tenant_id, user_id, role, invited_by, status, joined_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, tenant_id, user_id, role, invited_by, joined_at, status, created_at
`

type CreateTenantMemberParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    string             `json:"user_id"`
	Role      TenantMemberRole   `json:"role"`
	InvitedBy pgtype.Text        `json:"invited_by"`
	Status    TenantMemberStatus `json:"status"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) CreateTenantMember(ctx context.Context, arg CreateTenantMemberParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, createTenantMember,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
		arg.Status,
		arg.JoinedAt,
	)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, plan, stripe_customer_id, stripe_subscription_id, owner_id, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByOwnerID = `-- name: GetTenantByOwnerID :one
SELECT id, name, slug, plan, stripe_customer_id, stripe_subscription_id, owner_id, created_at, updated_at FROM tenants WHERE owner_id = $1
`

func (q *Queries) GetTenantByOwnerID(ctx context.Context, ownerID string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByOwnerID, ownerID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, plan, stripe_customer_id, stripe_subscription_id, owner_id, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantForUser = `-- name: GetTenantForUser :one
SELECT t.id, t.name, t.slug, t.plan, t.stripe_customer_id, t.stripe_subscription_id, t.owner_id,
       tm.role, t.created_at, t.updated_at
FROM tenants t
JOIN tenant_members tm ON tm.tenant_id = t.id
WHERE tm.user_id = $1 AND tm.status = 'active'
LIMIT 1
`

type GetTenantForUserRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Plan                 UserPlan           `json:"plan"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	OwnerID              string             `json:"owner_id"`
	Role                 TenantMemberRole   `json:"role"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTenantForUser(ctx context.Context, userID string) (GetTenantForUserRow, error) {
	row := q.db.QueryRow(ctx, getTenantForUser, userID)
	var i GetTenantForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.OwnerID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantInviteByID = `-- name: GetTenantInviteByID :one
SELECT id, tenant_id, email, role, token, invited_by, status, expires_at, created_at FROM tenant_invites WHERE id = $1
`

func (q *Queries) GetTenantInviteByID(ctx context.Context, id pgtype.UUID) (TenantInvite, error) {
	row := q.db.QueryRow(ctx, getTenantInviteByID, id)
	var i TenantInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantInviteByToken = `-- name: GetTenantInviteByToken :one
SELECT id, tenant_id, email, role, token, invited_by, status, expires_at, created_at FROM tenant_invites WHERE token = $1
`

func (q *Queries) GetTenantInviteByToken(ctx context.Context, token string) (TenantInvite, error) {
	row := q.db.QueryRow(ctx, getTenantInviteByToken, token)
	var i TenantInvite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantMemberByUserID = `-- name: GetTenantMemberByUserID :one
SELECT id, tenant_id, user_id, role, invited_by, joined_at, status, created_at FROM tenant_members WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantMemberByUserIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   string      `json:"user_id"`
}

func (q *Queries) GetTenantMemberByUserID(ctx context.Context, arg GetTenantMemberByUserIDParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, getTenantMemberByUserID, arg.TenantID, arg.UserID)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listTenantInvites = `-- name: ListTenantInvites :many
SELECT id, tenant_id, email, role, token, invited_by, status, expires_at, created_at FROM tenant_invites WHERE tenant_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListTenantInvites(ctx context.Context, tenantID pgtype.UUID) ([]TenantInvite, error) {
	rows, err := q.db.Query(ctx, listTenantInvites, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantInvite{}
	for rows.Next() {
		var i TenantInvite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT tm.id, tm.tenant_id, tm.user_id, tm.role, tm.invited_by, tm.joined_at, tm.status, tm.created_at, u.email AS member_email, u.name AS member_name, u.avatar_url AS member_avatar_url
FROM tenant_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = $1 AND tm.status = 'active'
ORDER BY tm.created_at ASC
`

type ListTenantMembersRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	UserID          string             `json:"user_id"`
	Role            TenantMemberRole   `json:"role"`
	InvitedBy       pgtype.Text        `json:"invited_by"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
	Status          TenantMemberStatus `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MemberEmail     string             `json:"member_email"`
	MemberName      string             `json:"member_name"`
	MemberAvatarUrl pgtype.Text        `json:"member_avatar_url"`
}

func (q *Queries) ListTenantMembers(ctx context.Context, tenantID pgtype.UUID) ([]ListTenantMembersRow, error) {
	rows, err := q.db.Query(ctx, listTenantMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantMembersRow{}
	for rows.Next() {
		var i ListTenantMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.Status,
			&i.CreatedAt,
			&i.MemberEmail,
			&i.MemberName,
			&i.MemberAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsForUser = `-- name: ListTenantsForUser :many
SELECT t.id, t.name, t.slug, t.plan, t.stripe_customer_id, t.stripe_subscription_id, t.owner_id, t.created_at, t.updated_at, tm.role FROM tenants t
JOIN tenant_members tm ON tm.tenant_id = t.id
WHERE tm.user_id = $1 AND tm.status = 'active'
ORDER BY t.created_at ASC
`

type ListTenantsForUserRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Plan                 UserPlan           `json:"plan"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	OwnerID              string             `json:"owner_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Role                 TenantMemberRole   `json:"role"`
}

func (q *Queries) ListTenantsForUser(ctx context.Context, userID string) ([]ListTenantsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTenantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsForUserRow{}
	for rows.Next() {
		var i ListTenantsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTenantMember = `-- name: RemoveTenantMember :exec
UPDATE tenant_members SET status = 'removed' WHERE id = $1
`

func (q *Queries) RemoveTenantMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTenantMember, id)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET name = $2, slug = $3 WHERE id = $1 RETURNING id, name, slug, plan, stripe_customer_id, stripe_subscription_id, owner_id, created_at, updated_at
`

type UpdateTenantParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant, arg.ID, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantPlan = `-- name: UpdateTenantPlan :exec
UPDATE tenants SET plan = $2, stripe_customer_id = $3, stripe_subscription_id = $4 WHERE id = $1
`

type UpdateTenantPlanParams struct {
	ID                   pgtype.UUID `json:"id"`
	Plan                 UserPlan    `json:"plan"`
	StripeCustomerID     pgtype.Text `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
}

func (q *Queries) UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) error {
	_, err := q.db.Exec(ctx, updateTenantPlan,
		arg.ID,
		arg.Plan,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
	)
	return err
}
