// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timelines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTimelineEntriesByTimelineID = `-- name: CountTimelineEntriesByTimelineID :one
SELECT COUNT(*) FROM timeline_entries WHERE timeline_id = $1
`

func (q *Queries) CountTimelineEntriesByTimelineID(ctx context.Context, timelineID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTimelineEntriesByTimelineID, timelineID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTimelinesByUserID = `-- name: CountTimelinesByUserID :one
SELECT COUNT(*) FROM timelines WHERE user_id = $1
`

func (q *Queries) CountTimelinesByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTimelinesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTimeline = `-- name: CreateTimeline :one
INSERT INTO timelines (user_id, space_id, slug, title, description, category, cta_text, cta_url, is_public)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, space_id, slug, title, description, category, cta_text, cta_url, is_public, created_at, updated_at
`

type CreateTimelineParams struct {
	UserID      string      `json:"user_id"`
	SpaceID     pgtype.UUID `json:"space_id"`
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Category    pgtype.Text `json:"category"`
	CtaText     pgtype.Text `json:"cta_text"`
	CtaUrl      pgtype.Text `json:"cta_url"`
	IsPublic    bool        `json:"is_public"`
}

func (q *Queries) CreateTimeline(ctx context.Context, arg CreateTimelineParams) (Timeline, error) {
	row := q.db.QueryRow(ctx, createTimeline,
		arg.UserID,
		arg.SpaceID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.CtaText,
		arg.CtaUrl,
		arg.IsPublic,
	)
	var i Timeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpaceID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CtaText,
		&i.CtaUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTimelineEntry = `-- name: CreateTimelineEntry :one
INSERT INTO timeline_entries (timeline_id, image_url, label, date, note, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, timeline_id, image_url, label, date, note, sort_order, created_at
`

type CreateTimelineEntryParams struct {
	TimelineID pgtype.UUID `json:"timeline_id"`
	ImageUrl   string      `json:"image_url"`
	Label      string      `json:"label"`
	Date       pgtype.Date `json:"date"`
	Note       pgtype.Text `json:"note"`
	SortOrder  int32       `json:"sort_order"`
}

func (q *Queries) CreateTimelineEntry(ctx context.Context, arg CreateTimelineEntryParams) (TimelineEntry, error) {
	row := q.db.QueryRow(ctx, createTimelineEntry,
		arg.TimelineID,
		arg.ImageUrl,
		arg.Label,
		arg.Date,
		arg.Note,
		arg.SortOrder,
	)
	var i TimelineEntry
	err := row.Scan(
		&i.ID,
		&i.TimelineID,
		&i.ImageUrl,
		&i.Label,
		&i.Date,
		&i.Note,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTimeline = `-- name: DeleteTimeline :exec
DELETE FROM timelines WHERE id = $1
`

func (q *Queries) DeleteTimeline(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimeline, id)
	return err
}

const deleteTimelineEntry = `-- name: DeleteTimelineEntry :exec
DELETE FROM timeline_entries WHERE id = $1
`

func (q *Queries) DeleteTimelineEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimelineEntry, id)
	return err
}

const getPublicTimelineBySlug = `-- name: GetPublicTimelineBySlug :one
SELECT id, user_id, space_id, slug, title, description, category, cta_text, cta_url, is_public, created_at, updated_at FROM timelines WHERE slug = $1 AND is_public = true
`

func (q *Queries) GetPublicTimelineBySlug(ctx context.Context, slug string) (Timeline, error) {
	row := q.db.QueryRow(ctx, getPublicTimelineBySlug, slug)
	var i Timeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpaceID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CtaText,
		&i.CtaUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimelineByID = `-- name: GetTimelineByID :one
SELECT id, user_id, space_id, slug, title, description, category, cta_text, cta_url, is_public, created_at, updated_at FROM timelines WHERE id = $1
`

func (q *Queries) GetTimelineByID(ctx context.Context, id pgtype.UUID) (Timeline, error) {
	row := q.db.QueryRow(ctx, getTimelineByID, id)
	var i Timeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpaceID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CtaText,
		&i.CtaUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimelineBySlug = `-- name: GetTimelineBySlug :one
SELECT id, user_id, space_id, slug, title, description, category, cta_text, cta_url, is_public, created_at, updated_at FROM timelines WHERE slug = $1
`

func (q *Queries) GetTimelineBySlug(ctx context.Context, slug string) (Timeline, error) {
	row := q.db.QueryRow(ctx, getTimelineBySlug, slug)
	var i Timeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpaceID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CtaText,
		&i.CtaUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTimelineEntries = `-- name: ListTimelineEntries :many
SELECT id, timeline_id, image_url, label, date, note, sort_order, created_at FROM timeline_entries WHERE timeline_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) ListTimelineEntries(ctx context.Context, timelineID pgtype.UUID) ([]TimelineEntry, error) {
	rows, err := q.db.Query(ctx, listTimelineEntries, timelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineEntry{}
	for rows.Next() {
		var i TimelineEntry
		if err := rows.Scan(
			&i.ID,
			&i.TimelineID,
			&i.ImageUrl,
			&i.Label,
			&i.Date,
			&i.Note,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelinesByUserIDs = `-- name: ListTimelinesByUserIDs :many
SELECT id, user_id, space_id, slug, title, description, category, cta_text, cta_url, is_public, created_at, updated_at FROM timelines WHERE user_id = ANY($1::text[]) ORDER BY created_at DESC
`

func (q *Queries) ListTimelinesByUserIDs(ctx context.Context, dollar_1 []string) ([]Timeline, error) {
	rows, err := q.db.Query(ctx, listTimelinesByUserIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Timeline{}
	for rows.Next() {
		var i Timeline
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SpaceID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CtaText,
			&i.CtaUrl,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderTimelineEntry = `-- name: ReorderTimelineEntry :exec
UPDATE timeline_entries SET sort_order = $2 WHERE id = $1
`

type ReorderTimelineEntryParams struct {
	ID        pgtype.UUID `json:"id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) ReorderTimelineEntry(ctx context.Context, arg ReorderTimelineEntryParams) error {
	_, err := q.db.Exec(ctx, reorderTimelineEntry, arg.ID, arg.SortOrder)
	return err
}

const updateTimeline = `-- name: UpdateTimeline :one
UPDATE timelines SET title = $2, description = $3, category = $4, cta_text = $5, cta_url = $6, is_public = $7
WHERE id = $1 RETURNING id, user_id, space_id, slug, title, description, category, cta_text, cta_url, is_public, created_at, updated_at
`

type UpdateTimelineParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Category    pgtype.Text `json:"category"`
	CtaText     pgtype.Text `json:"cta_text"`
	CtaUrl      pgtype.Text `json:"cta_url"`
	IsPublic    bool        `json:"is_public"`
}

func (q *Queries) UpdateTimeline(ctx context.Context, arg UpdateTimelineParams) (Timeline, error) {
	row := q.db.QueryRow(ctx, updateTimeline,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.CtaText,
		arg.CtaUrl,
		arg.IsPublic,
	)
	var i Timeline
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpaceID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CtaText,
		&i.CtaUrl,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTimelineEntry = `-- name: UpdateTimelineEntry :one
UPDATE timeline_entries SET image_url = $2, label = $3, date = $4, note = $5
WHERE id = $1 RETURNING id, timeline_id, image_url, label, date, note, sort_order, created_at
`

type UpdateTimelineEntryParams struct {
	ID       pgtype.UUID `json:"id"`
	ImageUrl string      `json:"image_url"`
	Label    string      `json:"label"`
	Date     pgtype.Date `json:"date"`
	Note     pgtype.Text `json:"note"`
}

func (q *Queries) UpdateTimelineEntry(ctx context.Context, arg UpdateTimelineEntryParams) (TimelineEntry, error) {
	row := q.db.QueryRow(ctx, updateTimelineEntry,
		arg.ID,
		arg.ImageUrl,
		arg.Label,
		arg.Date,
		arg.Note,
	)
	var i TimelineEntry
	err := row.Scan(
		&i.ID,
		&i.TimelineID,
		&i.ImageUrl,
		&i.Label,
		&i.Date,
		&i.Note,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
