// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUploadRequestsByUserIDThisMonth = `-- name: CountUploadRequestsByUserIDThisMonth :one
SELECT COUNT(*) FROM upload_requests
WHERE user_id = $1 AND created_at >= date_trunc('month', now())
`

func (q *Queries) CountUploadRequestsByUserIDThisMonth(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUploadRequestsByUserIDThisMonth, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUploadRequest = `-- name: CreateUploadRequest :one
INSERT INTO upload_requests (space_id, user_id, token, client_name, client_email, client_phone, request_type, instruction_note, service_type, sent_via)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, space_id, user_id, token, client_name, client_email, client_phone, request_type, instruction_note, before_image_url, after_image_url, review_rating, review_content, service_type, status, sent_via, reminder_sent_at, submitted_at, reviewed_at, expires_at, created_at, updated_at
`

type CreateUploadRequestParams struct {
	SpaceID         pgtype.UUID          `json:"space_id"`
	UserID          string               `json:"user_id"`
	Token           string               `json:"token"`
	ClientName      pgtype.Text          `json:"client_name"`
	ClientEmail     pgtype.Text          `json:"client_email"`
	ClientPhone     pgtype.Text          `json:"client_phone"`
	RequestType     UploadRequestType    `json:"request_type"`
	InstructionNote pgtype.Text          `json:"instruction_note"`
	ServiceType     pgtype.Text          `json:"service_type"`
	SentVia         UploadRequestSentVia `json:"sent_via"`
}

func (q *Queries) CreateUploadRequest(ctx context.Context, arg CreateUploadRequestParams) (UploadRequest, error) {
	row := q.db.QueryRow(ctx, createUploadRequest,
		arg.SpaceID,
		arg.UserID,
		arg.Token,
		arg.ClientName,
		arg.ClientEmail,
		arg.ClientPhone,
		arg.RequestType,
		arg.InstructionNote,
		arg.ServiceType,
		arg.SentVia,
	)
	var i UploadRequest
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Token,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.RequestType,
		&i.InstructionNote,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.ReviewRating,
		&i.ReviewContent,
		&i.ServiceType,
		&i.Status,
		&i.SentVia,
		&i.ReminderSentAt,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadRequestByID = `-- name: GetUploadRequestByID :one
SELECT id, space_id, user_id, token, client_name, client_email, client_phone, request_type, instruction_note, before_image_url, after_image_url, review_rating, review_content, service_type, status, sent_via, reminder_sent_at, submitted_at, reviewed_at, expires_at, created_at, updated_at FROM upload_requests WHERE id = $1
`

func (q *Queries) GetUploadRequestByID(ctx context.Context, id pgtype.UUID) (UploadRequest, error) {
	row := q.db.QueryRow(ctx, getUploadRequestByID, id)
	var i UploadRequest
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Token,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.RequestType,
		&i.InstructionNote,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.ReviewRating,
		&i.ReviewContent,
		&i.ServiceType,
		&i.Status,
		&i.SentVia,
		&i.ReminderSentAt,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadRequestByToken = `-- name: GetUploadRequestByToken :one
SELECT id, space_id, user_id, token, client_name, client_email, client_phone, request_type, instruction_note, before_image_url, after_image_url, review_rating, review_content, service_type, status, sent_via, reminder_sent_at, submitted_at, reviewed_at, expires_at, created_at, updated_at FROM upload_requests WHERE token = $1
`

func (q *Queries) GetUploadRequestByToken(ctx context.Context, token string) (UploadRequest, error) {
	row := q.db.QueryRow(ctx, getUploadRequestByToken, token)
	var i UploadRequest
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Token,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.RequestType,
		&i.InstructionNote,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.ReviewRating,
		&i.ReviewContent,
		&i.ServiceType,
		&i.Status,
		&i.SentVia,
		&i.ReminderSentAt,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUploadRequestsBySpaceID = `-- name: ListUploadRequestsBySpaceID :many
SELECT id, space_id, user_id, token, client_name, client_email, client_phone, request_type, instruction_note, before_image_url, after_image_url, review_rating, review_content, service_type, status, sent_via, reminder_sent_at, submitted_at, reviewed_at, expires_at, created_at, updated_at FROM upload_requests WHERE space_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUploadRequestsBySpaceID(ctx context.Context, spaceID pgtype.UUID) ([]UploadRequest, error) {
	rows, err := q.db.Query(ctx, listUploadRequestsBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadRequest{}
	for rows.Next() {
		var i UploadRequest
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.UserID,
			&i.Token,
			&i.ClientName,
			&i.ClientEmail,
			&i.ClientPhone,
			&i.RequestType,
			&i.InstructionNote,
			&i.BeforeImageUrl,
			&i.AfterImageUrl,
			&i.ReviewRating,
			&i.ReviewContent,
			&i.ServiceType,
			&i.Status,
			&i.SentVia,
			&i.ReminderSentAt,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUploadRequestReminderSent = `-- name: UpdateUploadRequestReminderSent :exec
UPDATE upload_requests SET reminder_sent_at = now() WHERE id = $1
`

func (q *Queries) UpdateUploadRequestReminderSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUploadRequestReminderSent, id)
	return err
}

const updateUploadRequestReviewed = `-- name: UpdateUploadRequestReviewed :one
UPDATE upload_requests SET status = $2, reviewed_at = now() WHERE id = $1 RETURNING id, space_id, user_id, token, client_name, client_email, client_phone, request_type, instruction_note, before_image_url, after_image_url, review_rating, review_content, service_type, status, sent_via, reminder_sent_at, submitted_at, reviewed_at, expires_at, created_at, updated_at
`

type UpdateUploadRequestReviewedParams struct {
	ID     pgtype.UUID         `json:"id"`
	Status UploadRequestStatus `json:"status"`
}

func (q *Queries) UpdateUploadRequestReviewed(ctx context.Context, arg UpdateUploadRequestReviewedParams) (UploadRequest, error) {
	row := q.db.QueryRow(ctx, updateUploadRequestReviewed, arg.ID, arg.Status)
	var i UploadRequest
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Token,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.RequestType,
		&i.InstructionNote,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.ReviewRating,
		&i.ReviewContent,
		&i.ServiceType,
		&i.Status,
		&i.SentVia,
		&i.ReminderSentAt,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadRequestStatus = `-- name: UpdateUploadRequestStatus :one
UPDATE upload_requests SET status = $2 WHERE id = $1 RETURNING id, space_id, user_id, token, client_name, client_email, client_phone, request_type, instruction_note, before_image_url, after_image_url, review_rating, review_content, service_type, status, sent_via, reminder_sent_at, submitted_at, reviewed_at, expires_at, created_at, updated_at
`

type UpdateUploadRequestStatusParams struct {
	ID     pgtype.UUID         `json:"id"`
	Status UploadRequestStatus `json:"status"`
}

func (q *Queries) UpdateUploadRequestStatus(ctx context.Context, arg UpdateUploadRequestStatusParams) (UploadRequest, error) {
	row := q.db.QueryRow(ctx, updateUploadRequestStatus, arg.ID, arg.Status)
	var i UploadRequest
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Token,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.RequestType,
		&i.InstructionNote,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.ReviewRating,
		&i.ReviewContent,
		&i.ServiceType,
		&i.Status,
		&i.SentVia,
		&i.ReminderSentAt,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadRequestSubmission = `-- name: UpdateUploadRequestSubmission :one
UPDATE upload_requests SET
    before_image_url = $2, after_image_url = $3,
    review_rating = $4, review_content = $5,
    status = 'submitted', submitted_at = now()
WHERE id = $1 RETURNING id, space_id, user_id, token, client_name, client_email, client_phone, request_type, instruction_note, before_image_url, after_image_url, review_rating, review_content, service_type, status, sent_via, reminder_sent_at, submitted_at, reviewed_at, expires_at, created_at, updated_at
`

type UpdateUploadRequestSubmissionParams struct {
	ID             pgtype.UUID `json:"id"`
	BeforeImageUrl pgtype.Text `json:"before_image_url"`
	AfterImageUrl  pgtype.Text `json:"after_image_url"`
	ReviewRating   pgtype.Int4 `json:"review_rating"`
	ReviewContent  pgtype.Text `json:"review_content"`
}

func (q *Queries) UpdateUploadRequestSubmission(ctx context.Context, arg UpdateUploadRequestSubmissionParams) (UploadRequest, error) {
	row := q.db.QueryRow(ctx, updateUploadRequestSubmission,
		arg.ID,
		arg.BeforeImageUrl,
		arg.AfterImageUrl,
		arg.ReviewRating,
		arg.ReviewContent,
	)
	var i UploadRequest
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Token,
		&i.ClientName,
		&i.ClientEmail,
		&i.ClientPhone,
		&i.RequestType,
		&i.InstructionNote,
		&i.BeforeImageUrl,
		&i.AfterImageUrl,
		&i.ReviewRating,
		&i.ReviewContent,
		&i.ServiceType,
		&i.Status,
		&i.SentVia,
		&i.ReminderSentAt,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
