// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, email, name, avatar_url, created_at, updated_at, custom_subdomain, api_key FROM users WHERE api_key = $1
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomSubdomain,
		&i.ApiKey,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, avatar_url, created_at, updated_at, custom_subdomain, api_key FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomSubdomain,
		&i.ApiKey,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, avatar_url, created_at, updated_at, custom_subdomain, api_key FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomSubdomain,
		&i.ApiKey,
	)
	return i, err
}

const getUserBySubdomain = `-- name: GetUserBySubdomain :one
SELECT id, email, name, avatar_url, created_at, updated_at, custom_subdomain, api_key FROM users WHERE custom_subdomain = $1
`

func (q *Queries) GetUserBySubdomain(ctx context.Context, customSubdomain pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubdomain, customSubdomain)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomSubdomain,
		&i.ApiKey,
	)
	return i, err
}

const setUserAPIKey = `-- name: SetUserAPIKey :one
UPDATE users SET api_key = $2 WHERE id = $1 RETURNING id, email, name, avatar_url, created_at, updated_at, custom_subdomain, api_key
`

type SetUserAPIKeyParams struct {
	ID     string      `json:"id"`
	ApiKey pgtype.Text `json:"api_key"`
}

func (q *Queries) SetUserAPIKey(ctx context.Context, arg SetUserAPIKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAPIKey, arg.ID, arg.ApiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomSubdomain,
		&i.ApiKey,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $2, avatar_url = $3 WHERE id = $1 RETURNING id, email, name, avatar_url, created_at, updated_at, custom_subdomain, api_key
`

type UpdateUserParams struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomSubdomain,
		&i.ApiKey,
	)
	return i, err
}

const updateUserSubdomain = `-- name: UpdateUserSubdomain :one
UPDATE users SET custom_subdomain = $2 WHERE id = $1 RETURNING id, email, name, avatar_url, created_at, updated_at, custom_subdomain, api_key
`

type UpdateUserSubdomainParams struct {
	ID              string      `json:"id"`
	CustomSubdomain pgtype.Text `json:"custom_subdomain"`
}

func (q *Queries) UpdateUserSubdomain(ctx context.Context, arg UpdateUserSubdomainParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSubdomain, arg.ID, arg.CustomSubdomain)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomSubdomain,
		&i.ApiKey,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    email = CASE WHEN EXCLUDED.email = '' THEN users.email ELSE EXCLUDED.email END,
    name = CASE WHEN EXCLUDED.name = '' THEN users.name ELSE EXCLUDED.name END,
    avatar_url = CASE WHEN EXCLUDED.avatar_url IS NULL THEN users.avatar_url ELSE EXCLUDED.avatar_url END,
    updated_at = now()
RETURNING id, email, name, avatar_url, created_at, updated_at, custom_subdomain, api_key
`

type UpsertUserParams struct {
	ID        string      `json:"id"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomSubdomain,
		&i.ApiKey,
	)
	return i, err
}
